fixed bug

diff --git a/.github/workflows/deploy-after-tests.yml b/.github/workflows/deploy-after-tests.yml
--- a/.github/workflows/deploy-after-tests.yml
+++ b/.github/workflows/deploy-after-tests.yml
@@ -6,10 +6,17 @@ on:
 
 jobs:
     deploy:
-        runs-on: ubuntu-latest
-        if: ${{ github.event.workflow_run.conclusion == 'success' }}    
+        runs-on: ubuntu-latest    
         steps:
+
+            - name: Print Warning Message
+              if: ${{ github.event.workflow_run.conclusion != 'success' }}
+              run: |
+                echo "::warning::Tests failed. Deployment will not proceed."
+                exit 1
+
             - name: Print Deployment Message
+              if: ${{ github.event.workflow_run.conclusion == 'success' }}
               run: |
                 echo "Deploy workflow triggered."
               
